/** @brief One DAG transition to a child formed by adding one physical edge. */
struct dagTransition
{
    int childIndex;
    uint32_t addedEdge;

    dagTransition(int childNodeIndex, size_t addedEdgeIndex):
        childIndex(childNodeIndex),
        addedEdge(static_cast<uint32_t>(addedEdgeIndex))
    {
        if (addedEdgeIndex > numeric_limits<uint32_t>::max())
            throw length_error("DAG edge index exceeds transition capacity");
    }
};

static_assert(sizeof(dagTransition) == sizeof(uint64_t));

constexpr uint32_t unassignedDagTransitionOffset =
    numeric_limits<uint32_t>::max();

/** @brief A compact node retained while the initial DAG is being built. */
struct initialDagNode
{
    uint32_t transitionOffset = unassignedDagTransitionOffset;
    uint32_t transitionCount = 0;
};

/**
 * @brief One initial-DAG level with a mask uniqueness index and flat edges.
 *
 * Node indices are insertion-order positions in nodes. Each retained child has
 * exactly one incoming edge, and a parent is expanded once, so its transitions
 * form one contiguous span in transitions.
 */
struct initialDagLevel
{
    unordered_map<EdgeMask, int> maskIndices;
    vector<initialDagNode> nodes;
    vector<dagTransition> transitions;
};

/**
 * @brief A runtime DAG node
 *
 * Node masks are reconstructed by following transitions from a known parent.
 */
struct dagNode
{
    /// @brief the canonical form of the node
    int canonicalIndex = -1;
    /// @brief Contiguous child-transition range in the owning DAG level
    uint32_t transitionOffset = 0;
    uint32_t transitionCount = 0;

    dagNode() = default;

    dagNode(int sourceCanonicalIndex, uint32_t childOffset, uint32_t childCount):
        canonicalIndex(sourceCanonicalIndex),
        transitionOffset(childOffset),
        transitionCount(childCount) {}
};

static_assert(sizeof(dagNode) == 3 * sizeof(uint32_t));

/** @brief Runtime DAG level stored in compressed sparse row form. */
struct dagLevel
{
    vector<dagNode> nodes;
    vector<dagTransition> transitions;
};

/**
 * @brief Converts the tempDAG generated by initialRecursiveEnumeration into the more efficient DAG
 * used on all subsequent passes of the algorithm
 *
 * @param output Runtime DAG populated from tempDag
 */
void convertDag(
    vector<initialDagLevel> &tempDag,
    vector<dagLevel> &output
)
{
    const size_t universeEdgeCount = searchUniverseEdgeList().size();
    output.clear();
    output.resize(tempDag.size());
    if (tempDag.size() < 2) return;

    auto transitionSpan = [&](
        const initialDagLevel &level,
        const initialDagNode &node
    ) -> pair<uint32_t, uint32_t> {
        if (node.transitionOffset == unassignedDagTransitionOffset)
            return {0, 0};
        const size_t offset = node.transitionOffset;
        const size_t count = node.transitionCount;
        if (
            offset > level.transitions.size() ||
            count > level.transitions.size() - offset
        )
        {
            throw logic_error("DAG transition span is invalid");
        }
        return {node.transitionOffset, node.transitionCount};
    };

    auto validateTransitions = [universeEdgeCount](
        const initialDagLevel &level,
        const initialDagNode &node,
        size_t childLevelSize
    ) {
        if (node.transitionOffset == unassignedDagTransitionOffset) return;
        const size_t end = static_cast<size_t>(node.transitionOffset) +
            node.transitionCount;
        if (end > level.transitions.size())
        {
            throw logic_error("DAG transition span is invalid");
        }
        for (size_t index = node.transitionOffset; index < end; index++)
        {
            const dagTransition &transition = level.transitions[index];
            if (
                transition.childIndex < 0 ||
                static_cast<size_t>(transition.childIndex) >= childLevelSize
            )
            {
                throw logic_error("DAG transition target is missing");
            }
            if (transition.addedEdge >= universeEdgeCount)
            {
                throw logic_error("DAG transition edge is out of range");
            }
        }
    };

    initialDagLevel &rootLevel = tempDag[0];
    if (
        rootLevel.maskIndices.size() != universeEdgeCount ||
        rootLevel.nodes.size() != rootLevel.maskIndices.size()
    )
    {
        throw logic_error("DAG root count does not match the edge list");
    }
    output[0].nodes.resize(rootLevel.nodes.size());
    vector<bool> populatedRoots(rootLevel.nodes.size(), false);
    for (const auto &entry : rootLevel.maskIndices)
    {
        const EdgeMask &mask = entry.first;
        if (mask.count() != 1)
        {
            throw logic_error("DAG root must contain exactly one edge");
        }
        const size_t edge = mask.findFirst();
        if (edge >= rootLevel.nodes.size() || populatedRoots[edge])
        {
            throw logic_error("DAG roots are not in physical edge order");
        }
        populatedRoots[edge] = true;
        const int nodeIndex = entry.second;
        if (
            nodeIndex < 0 ||
            static_cast<size_t>(nodeIndex) >= rootLevel.nodes.size()
        )
        {
            throw logic_error("DAG root index is invalid");
        }
        const initialDagNode &node = rootLevel.nodes[nodeIndex];
        validateTransitions(rootLevel, node, tempDag[1].nodes.size());
        const auto [offset, count] = transitionSpan(rootLevel, node);
        output[0].nodes[edge] = dagNode(-1, offset, count);
    }
    output[0].transitions = std::move(rootLevel.transitions);

    for (size_t levelIndex = 1; levelIndex + 1 < tempDag.size(); levelIndex++)
    {
        initialDagLevel &level = tempDag[levelIndex];
        if (level.nodes.size() != level.maskIndices.size())
            throw logic_error("DAG level index is incomplete");
        output[levelIndex].nodes.resize(level.nodes.size());
        vector<bool> populatedNodes(level.nodes.size(), false);
        for (const auto &entry : level.maskIndices)
        {
            const int nodeIndex = entry.second;
            if (
                nodeIndex < 0 ||
                static_cast<size_t>(nodeIndex) >= level.nodes.size() ||
                populatedNodes[nodeIndex]
            )
            {
                throw logic_error("DAG node index is invalid");
            }
            populatedNodes[nodeIndex] = true;

            const auto canonical = bitsetHashTable.find(entry.first);
            if (canonical == bitsetHashTable.end())
            {
                throw logic_error("DAG node canonical index is missing");
            }
            const initialDagNode &node = level.nodes[nodeIndex];
            validateTransitions(
                level,
                node,
                tempDag[levelIndex + 1].nodes.size()
            );
            const auto [offset, count] = transitionSpan(level, node);
            output[levelIndex].nodes[nodeIndex] = dagNode(
                canonical->second.first,
                offset,
                count
            );
        }
        output[levelIndex].transitions = std::move(level.transitions);
    }
}
