/** @brief One DAG transition to a child formed by adding one physical edge. */
struct dagTransition
{
    int childIndex;
    uint32_t addedEdge;

    dagTransition(int _childIndex, size_t _addedEdge):
        childIndex(_childIndex),
        addedEdge(static_cast<uint32_t>(_addedEdge)) {}
};

static_assert(sizeof(dagTransition) == sizeof(uint64_t));

/**
 * @brief A node retained while the initial enumeration DAG is being built.
 *
 * The mask itself lives only in initialDagLevel's unordered-map key. Children
 * are assigned stable, level-local indices as they are retained, so an edge
 * needs only the same compact transition used by the runtime DAG. Runtime DAG
 * levels are addressed through those indices and are never traversal-ordered.
 */
struct initialDagNode
{
    int index = -1;
    vector<dagTransition> transitions;
};

using initialDagLevel = std::unordered_map<EdgeMask, initialDagNode>;

/**
 * @brief A runtime DAG node
 *
 * Node masks are reconstructed by following transitions from a known parent.
 */
struct dagNode
{
    /// @brief the canonical form of the node
    int ix = -1;
    /// @brief size + 1 nodes generated by adding one edge to this node
    vector<dagTransition> transitions;

    dagNode() = default;

    dagNode(int _ix, vector<dagTransition> &&_transitions):
        ix(_ix), transitions(std::move(_transitions)) {}
};

/// DAG used to enumerate duplicatable subgraphs
vector<vector<dagNode> > DAG;

/**
 * @brief Converts the tempDAG generated by initialRecursiveEnumeration into the more efficient DAG 
 * used on all subsequent passes of the algorithm
 * 
 */
void convertDag(vector<initialDagLevel> &tempDag)
{
    DAG.clear();
    DAG.resize(tempDag.size());
    if (tempDag.size() < 2) return;

    auto validateTransitions = [&](
        const initialDagNode &node,
        size_t childLevelSize
    ) {
        for (const dagTransition &transition : node.transitions)
        {
            if (
                transition.childIndex < 0 ||
                static_cast<size_t>(transition.childIndex) >= childLevelSize
            )
            {
                throw logic_error("DAG transition target is missing");
            }
            if (transition.addedEdge >= univEdgeList.size())
            {
                throw logic_error("DAG transition edge is out of range");
            }
        }
    };

    initialDagLevel &rootLevel = tempDag[0];
    if (rootLevel.size() != univEdgeList.size())
    {
        throw logic_error("DAG root count does not match the edge list");
    }
    DAG[0].resize(rootLevel.size());
    vector<bool> populatedRoots(rootLevel.size(), false);
    for (auto &entry : rootLevel)
    {
        const EdgeMask &mask = entry.first;
        if (mask.count() != 1)
        {
            throw logic_error("DAG root must contain exactly one edge");
        }
        const size_t edge = mask.findFirst();
        if (edge >= rootLevel.size() || populatedRoots[edge])
        {
            throw logic_error("DAG roots are not in physical edge order");
        }
        populatedRoots[edge] = true;
        initialDagNode &node = entry.second;
        validateTransitions(node, tempDag[1].size());
        DAG[0][edge] = dagNode(-1, std::move(node.transitions));
    }

    for (size_t i = 1; i + 1 < tempDag.size(); i++)
    {
        initialDagLevel &level = tempDag[i];
        DAG[i].resize(level.size());
        vector<bool> populatedNodes(level.size(), false);
        for (auto &entry : level)
        {
            initialDagNode &node = entry.second;
            if (
                node.index < 0 ||
                static_cast<size_t>(node.index) >= level.size() ||
                populatedNodes[node.index]
            )
            {
                throw logic_error("DAG node index is invalid");
            }
            populatedNodes[node.index] = true;

            const auto canonical = bitsetHashTable.find(entry.first);
            if (canonical == bitsetHashTable.end())
            {
                throw logic_error("DAG node canonical index is missing");
            }
            validateTransitions(node, tempDag[i + 1].size());
            DAG[i][node.index] = dagNode(
                canonical->second.first,
                std::move(node.transitions)
            );
        }
    }
}
