/** @brief One DAG transition to a child formed by adding one physical edge. */
struct dagTransition
{
    int childIndex;
    uint16_t addedEdge;

    dagTransition(int _childIndex, size_t _addedEdge):
        childIndex(_childIndex),
        addedEdge(static_cast<uint16_t>(_addedEdge)) {}
};

static_assert(
    MASK_BIT_CAPACITY <=
    static_cast<size_t>(numeric_limits<uint16_t>::max()) + 1
);

/**
 * @brief A runtime DAG node
 *
 * Node masks are reconstructed by following transitions from a known parent.
 */
struct dagNode
{
    /// @brief the canonical form of the node
    int ix;
    /// @brief size + 1 nodes generated by adding one edge to this node
    vector<dagTransition> transitions;

    dagNode(
        const EdgeMask &parentMask,
        int _ix,
        const vector<EdgeMask> &children,
        const std::unordered_map<EdgeMask, int> &bitsetToIndex
    ):
        ix(_ix)
    {
        transitions.reserve(children.size());
        for (const EdgeMask &childMask : children)
        {
            const auto child = bitsetToIndex.find(childMask);
            if (child == bitsetToIndex.end())
            {
                throw logic_error("DAG transition target is missing");
            }

            const EdgeMask added = childMask ^ parentMask;
            if (!childMask.contains(parentMask) || added.count() != 1)
            {
                throw logic_error("DAG transition must add exactly one edge");
            }

            size_t addedEdge = MASK_BIT_CAPACITY;
            forEachSetBitBelow(added, MASK_BIT_CAPACITY, [&](size_t edge) {
                addedEdge = edge;
            });
            if (addedEdge >= univEdgeList.size())
            {
                throw logic_error("DAG transition edge is out of range");
            }
            transitions.emplace_back(child->second, addedEdge);
        }
    }
};

/**
 * @brief Comparator used to put the one-edge root masks in physical edge order
 * 
 */
struct CompareDagMask {
    bool operator()(const EdgeMask &a, const EdgeMask &b) const {
        // Compare from most significant bit down to 0.
        for (size_t i = univEdgeList.size(); i-- > 0;) {
            if (a[i] ^ b[i])
            return b[i];
        }
        return 0;
    }
};

/// DAG used to enumerate duplicatable subgraphs
vector<vector<dagNode> > DAG;

/**
 * @brief Converts the tempDAG generated by initialRecursiveEnumeration into the more efficient DAG 
 * used on all subsequent passes of the algorithm
 * 
 */
void convertDag(vector<std::unordered_map<EdgeMask, pair<int, vector<EdgeMask> > > > & tempDag)
{
    DAG.resize(tempDag.size());
    vector<std::unordered_map<EdgeMask, int> > bitsetToIndex(tempDag.size());
    for (size_t i = 0; i < tempDag.size() - 1; i++)
    {
        if (i > 0) bitsetToIndex[i].reserve(tempDag[i].size());
        const auto &nextMap = tempDag[i + 1];
        for (auto it = tempDag[i].begin(); it != tempDag[i].end(); ++it)
        {
            vector<EdgeMask> &list = it->second.second;
            size_t trueSize = list.size();
            for (size_t j = 0; j < list.size(); j++)
            {
                if (nextMap.count(list[j]) == 0)
                {
                    list[j] = 0;
                    trueSize--;
                }
            }
            vector<EdgeMask> trueList(trueSize);
            size_t k = 0;
            for (size_t j = 0; j < list.size(); j++)
            {
                if (list[j] != 0)
                {
                    trueList[k] = list[j];
                    k++;
                }
            }
            it->second.second = std::move(trueList);
            if (i > 0)
            {
                it->second.first = bitsetHashTable[it->first].first;
                const int index = static_cast<int>(bitsetToIndex[i].size());
                bitsetToIndex[i].emplace(it->first, index);
            }
        }
    }
    if (DAG.size() > 1)
    {
        vector<EdgeMask> rootMasks;
        rootMasks.reserve(tempDag[0].size());
        for (const auto &entry : tempDag[0]) rootMasks.push_back(entry.first);
        sort(rootMasks.begin(), rootMasks.end(), CompareDagMask());
        if (rootMasks.size() != univEdgeList.size())
        {
            throw logic_error("DAG root count does not match the edge list");
        }
        for (size_t edge = 0; edge < rootMasks.size(); edge++)
        {
            if (rootMasks[edge].count() != 1 || !rootMasks[edge][edge])
            {
                throw logic_error("DAG roots are not in physical edge order");
            }
        }
        DAG[0].reserve(rootMasks.size());
        for (const EdgeMask &mask : rootMasks)
        {
            const auto &entry = tempDag[0].at(mask);
            DAG[0].emplace_back(mask, entry.first, entry.second, bitsetToIndex[1]);
        }
    }
    for (size_t i = 1; i + 1 < DAG.size(); i++)
    {
        DAG[i].reserve(tempDag[i].size());
        for (const auto &entry : tempDag[i])
        {
            DAG[i].emplace_back(
                entry.first,
                entry.second.first,
                entry.second.second,
                bitsetToIndex[i + 1]
            );
        }
    }
}
