if(NOT UNIX)
  return()
endif()

if(
  NOT DEFINED CPACK_TEMPORARY_INSTALL_DIRECTORY
  OR NOT IS_DIRECTORY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)
  message(FATAL_ERROR "CPack did not provide an archive staging directory")
endif()

file(
  GLOB_RECURSE PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES
  LIST_DIRECTORIES true
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/*"
)
list(
  PREPEND PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)

set(
  PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS
  OWNER_READ OWNER_WRITE OWNER_EXECUTE
  GROUP_READ GROUP_EXECUTE
  WORLD_READ WORLD_EXECUTE
)
set(
  PARALLELASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS
  OWNER_READ OWNER_WRITE
  GROUP_READ
  WORLD_READ
)

foreach(PARALLELASSEMBLYCPP_ARCHIVE_ENTRY IN LISTS PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES)
  if(IS_SYMLINK "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}")
    continue()
  endif()

  if(IS_DIRECTORY "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}")
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  elseif(
    PARALLELASSEMBLYCPP_ARCHIVE_ENTRY MATCHES "/bin/ParallelAssemblyCpp$"
    OR PARALLELASSEMBLYCPP_ARCHIVE_ENTRY
      MATCHES "/output/benchmarks/.+/run_benchmark\\.py$"
  )
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  else()
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS}
    )
  endif()
  file(
    CHMOD "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}"
    PERMISSIONS ${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS}
  )
endforeach()
