if(NOT UNIX)
  return()
endif()

if(
  NOT DEFINED CPACK_TEMPORARY_INSTALL_DIRECTORY
  OR NOT IS_DIRECTORY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)
  message(FATAL_ERROR "CPack did not provide an archive staging directory")
endif()

file(
  GLOB_RECURSE ASSEMBLYCPP_ARCHIVE_ENTRIES
  LIST_DIRECTORIES true
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/*"
)
list(
  PREPEND ASSEMBLYCPP_ARCHIVE_ENTRIES
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)

set(
  ASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS
  OWNER_READ OWNER_WRITE OWNER_EXECUTE
  GROUP_READ GROUP_EXECUTE
  WORLD_READ WORLD_EXECUTE
)
set(
  ASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS
  OWNER_READ OWNER_WRITE
  GROUP_READ
  WORLD_READ
)

foreach(ASSEMBLYCPP_ARCHIVE_ENTRY IN LISTS ASSEMBLYCPP_ARCHIVE_ENTRIES)
  if(IS_SYMLINK "${ASSEMBLYCPP_ARCHIVE_ENTRY}")
    continue()
  endif()

  if(IS_DIRECTORY "${ASSEMBLYCPP_ARCHIVE_ENTRY}")
    set(
      ASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${ASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  elseif(
    ASSEMBLYCPP_ARCHIVE_ENTRY MATCHES "/bin/AssemblyCpp$"
    OR ASSEMBLYCPP_ARCHIVE_ENTRY
      MATCHES "/output/benchmarks/.+/run_benchmark\\.py$"
  )
    set(
      ASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${ASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  else()
    set(
      ASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${ASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS}
    )
  endif()
  file(
    CHMOD "${ASSEMBLYCPP_ARCHIVE_ENTRY}"
    PERMISSIONS ${ASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS}
  )
endforeach()
