if(NOT UNIX)
  return()
endif()

if(
  NOT DEFINED CPACK_TEMPORARY_INSTALL_DIRECTORY
  OR NOT IS_DIRECTORY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)
  message(FATAL_ERROR "CPack did not provide an archive staging directory")
endif()

# Source archives have no installed executable. For binary archives, CPack's
# staging prefix depends on whether installation uses DESTDIR.
set(PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE "")
if(CPACK_INSTALL_CMAKE_PROJECTS)
  if(IS_ABSOLUTE "${CPACK_PARALLELASSEMBLYCPP_INSTALLED_EXECUTABLE}")
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE
      "${CPACK_PARALLELASSEMBLYCPP_INSTALLED_EXECUTABLE}"
    )
  elseif(CPACK_SET_DESTDIR)
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE
      "${CPACK_INSTALL_PREFIX}/${CPACK_PARALLELASSEMBLYCPP_INSTALLED_EXECUTABLE}"
    )
  else()
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE
      "${CPACK_PACKAGING_INSTALL_PREFIX}/${CPACK_PARALLELASSEMBLYCPP_INSTALLED_EXECUTABLE}"
    )
  endif()
  cmake_path(
    SET PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE NORMALIZE
    "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/${PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE}"
  )
endif()

file(
  GLOB_RECURSE PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES
  LIST_DIRECTORIES true
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/*"
)
list(
  PREPEND PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES
  "${CPACK_TEMPORARY_INSTALL_DIRECTORY}"
)

set(
  PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS
  OWNER_READ OWNER_WRITE OWNER_EXECUTE
  GROUP_READ GROUP_EXECUTE
  WORLD_READ WORLD_EXECUTE
)
set(
  PARALLELASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS
  OWNER_READ OWNER_WRITE
  GROUP_READ
  WORLD_READ
)

foreach(PARALLELASSEMBLYCPP_ARCHIVE_ENTRY IN LISTS PARALLELASSEMBLYCPP_ARCHIVE_ENTRIES)
  if(IS_SYMLINK "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}")
    continue()
  endif()

  if(IS_DIRECTORY "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}")
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  elseif(PARALLELASSEMBLYCPP_ARCHIVE_ENTRY STREQUAL PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE)
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_EXECUTABLE_PERMISSIONS}
    )
  else()
    set(
      PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS
      ${PARALLELASSEMBLYCPP_ARCHIVE_FILE_PERMISSIONS}
    )
  endif()
  file(
    CHMOD "${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY}"
    PERMISSIONS ${PARALLELASSEMBLYCPP_ARCHIVE_ENTRY_PERMISSIONS}
  )
endforeach()
